"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['walls_pyweek19.py']
DATA_FILES = ['levels.py', \
			'audio.py', \
			'block.gif', \
			'ghost.gif', \
			'goal.gif', \
			'goal_animation.gif', \
			'player.gif', \
			'spikes.gif', \
			'switch.gif', \
			'title.gif', \
			'hitwall_sfx.wav', \
			'levelend_sfx.wav', \
			'spikestep_sfx.wav', \
			'switchstep_sfx.wav', \
			'Pyweek_BG_1.wav']
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
